"""
Flask Web Application for Sign Language Alphabet Recognizer
Phase 3 Implementation
"""
import os
import sys

# Disable TensorFlow and OpenCV warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import io
import base64
from datetime import datetime
from flask import Flask, render_template, request, jsonify, send_file, redirect, url_for
from werkzeug.utils import secure_filename
import cv2
import numpy as np

# Import our custom modules
from ml_inference import MLInferenceEngine
from database import Database

app = Flask(__name__)
app.config['SECRET_KEY'] = 'your-secret-key-here'
app.config['UPLOAD_FOLDER'] = 'temp_uploads'
app.config['MAX_CONTENT_LENGTH'] = 10 * 1024 * 1024  # 10MB max file size
app.config['ALLOWED_EXTENSIONS'] = {'png', 'jpg', 'jpeg', 'gif', 'bmp'}

# Initialize ML Engine and Database
ml_engine = MLInferenceEngine()
db = Database()

# Create temp folder if it doesn't exist
os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)


def allowed_file(filename):
    """Check if file extension is allowed"""
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']


@app.route('/')
def index():
    """Homepage"""
    return render_template('index.html')


@app.route('/upload')
def upload_page():
    """Upload image page"""
    return render_template('upload.html')


@app.route('/webcam')
def webcam_page():
    """Webcam recognition page"""
    return render_template('webcam.html')


@app.route('/history')
def history_page():
    """View prediction history"""
    predictions = db.get_recent_predictions(limit=20)
    return render_template('history.html', predictions=predictions)


@app.route('/api/predict', methods=['POST'])
def predict():
    """
    API endpoint for image classification
    Accepts: multipart/form-data with 'image' file or base64 encoded image
    Returns: JSON with prediction results
    """
    try:
        # Check if image is in request
        if 'image' not in request.files and 'image_data' not in request.form:
            return jsonify({'error': 'No image provided'}), 400
        
        # Get image data
        if 'image' in request.files:
            file = request.files['image']
            
            # Validate file
            if file.filename == '':
                return jsonify({'error': 'No file selected'}), 400
            
            if not allowed_file(file.filename):
                return jsonify({'error': 'Invalid file type. Allowed: jpg, jpeg, png, gif, bmp'}), 400
            
            # Read image data
            image_bytes = file.read()
        else:
            # Handle base64 encoded image from webcam
            image_data = request.form['image_data']
            # Remove data URL prefix if present
            if 'base64,' in image_data:
                image_data = image_data.split('base64,')[1]
            image_bytes = base64.b64decode(image_data)
        
        # Convert to numpy array
        nparr = np.frombuffer(image_bytes, np.uint8)
        image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        
        if image is None:
            return jsonify({'error': 'Invalid image data'}), 400
        
        # Get prediction
        result = ml_engine.predict(image_bytes)
        
        # Store in database
        db.add_prediction(
            predicted_letter=result['prediction'],
            confidence=result['confidence']
        )
        
        # Clean up temp file if it was saved
        # (we're processing in memory, so no cleanup needed)
        
        return jsonify(result)
    
    except Exception as e:
        app.logger.error(f"Prediction error: {str(e)}")
        return jsonify({'error': f'Prediction failed: {str(e)}'}), 500


@app.route('/api/download_result', methods=['POST'])
def download_result():
    """
    Download prediction result as text file
    """
    try:
        data = request.get_json()
        prediction = data.get('prediction', 'Unknown')
        confidence = data.get('confidence', 0.0)
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # Create text content
        content = f"""Sign Language Recognition Result
================================

Predicted Letter: {prediction}
Confidence Score: {confidence:.2%}
Timestamp: {timestamp}

Generated by Sign Language Alphabet Recognizer
Phase 3 - Web Application
"""
        
        # Create file in memory
        output = io.BytesIO()
        output.write(content.encode('utf-8'))
        output.seek(0)
        
        filename = f"prediction_{prediction}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        
        return send_file(
            output,
            mimetype='text/plain',
            as_attachment=True,
            download_name=filename
        )
    
    except Exception as e:
        app.logger.error(f"Download error: {str(e)}")
        return jsonify({'error': f'Download failed: {str(e)}'}), 500


@app.route('/api/clear_history', methods=['POST'])
def clear_history():
    """Clear all prediction history"""
    try:
        db.clear_history()
        return jsonify({'message': 'History cleared successfully'})
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@app.route('/health')
def health():
    """Health check endpoint"""
    return jsonify({
        'status': 'healthy',
        'model_loaded': ml_engine.is_loaded(),
        'timestamp': datetime.now().isoformat()
    })


@app.errorhandler(413)
def too_large(e):
    """Handle file too large error"""
    return jsonify({'error': 'File too large. Maximum size is 10MB'}), 413


@app.errorhandler(404)
def not_found(e):
    """Handle 404 errors"""
    return render_template('404.html'), 404


@app.errorhandler(500)
def internal_error(e):
    """Handle 500 errors"""
    return render_template('500.html'), 500


if __name__ == '__main__':
    print("=" * 60)
    print("Sign Language Alphabet Recognizer - Web Application")
    print("Phase 3 Implementation")
    print("=" * 60)
    print(f"Model loaded: {ml_engine.is_loaded()}")
    print(f"Database initialized: {db.is_connected()}")
    print("Starting Flask server on http://localhost:5000")
    print("=" * 60)
    app.run(debug=True, host='0.0.0.0', port=5000)
